service: gimme-time

provider:
  name: aws
  runtime: nodejs10.x
  environment:
    STAGE: ${opt:stage}
    SHIFTLEFT_SPR_PATH: ./spr.json

functions:
  gimmetime:
    handler: sl.gimmetime
    events:
      - http:
          path: /time
          method: get
          request:
            parameters:
              querystrings:
                tz: true
